In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### Question 1

What's the version of NumPy that you installed?

In [3]:
np.__version__

'1.23.1'

### Question 2

How many records are in the dataset?

In [4]:
data.shape

(11914, 16)

### Question 3

Who are the most frequent car manufacturers (top-3) according to the dataset?

In [5]:
data["Make"].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

### Question 4

What's the number of unique Audi car models in the dataset?

In [6]:
data[data["Make"]=="Audi"]["Model"].nunique()

34

### Question 5

How many columns in the dataset have missing values?

In [7]:
data.isna().any().value_counts()

False    11
True      5
dtype: int64

### Question 6

   1) Find the median value of "Engine Cylinders" column in the dataset.
   2) Next, calculate the most frequent value of the same "Engine Cylinders".
   3) Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
   4) Now, calculate the median value of "Engine Cylinders" once again.


In [8]:
# 1.
np.median(data["Engine Cylinders"])

nan

In [9]:
# 2.
data["Engine Cylinders"].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [10]:
data.groupby("Engine Cylinders")["Engine Cylinders"].count().sort_values(ascending=False)

Engine Cylinders
4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [11]:
# 3.
data["Engine Cylinders"].fillna(4.0, inplace=True)

In [12]:
# 4.
np.median(data["Engine Cylinders"])

6.0

### Question 7

   1. Select all the "Lotus" cars from the dataset.
   2. Select only columns "Engine HP", "Engine Cylinders".
   3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
   4. Get the underlying NumPy array. Let's call it X.
   5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
   6. Compute the inverse of XTX.
   7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
   8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
   9. What's the value of the first element of w?


In [13]:
# 1
data_lotus = data[data["Make"] == "Lotus"]

In [14]:
# 2 & 3
data_lotus = data_lotus[["Engine HP", "Engine Cylinders"]].drop_duplicates()

In [15]:
# 4
X = np.array(data_lotus)
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [16]:
# 5 matrix multiplication = np.matmul()
XTX = np.matmul(X.T, X)
XTX


array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [20]:
# 6
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [18]:
# 7
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [28]:
# 8
w = np.matmul(XTX_inv, X.T)
w = w.dot(y)
w

array([  4.59494481, -63.56432501])

In [30]:
# 9
w[0]

4.594944810094551